### PR TITLE
Fix get_inlines method being ignored

### PR DESCRIPTION
**Pull request by pawnhearts**

### CODE REVIEW

**Comment by scottgigante** [comment]
@OskarPersson could you please merge this PR? It's been sitting here for almost a year now and would be a great addition to this package.

**Comment by OskarPersson** [comment]
@scottgigante I would like to see a test added first

**Comment by scottgigante** [comment]
I don't think anyone can write passing tests until https://github.com/OskarPersson/django-nested-inline/pull/161 is merged.. anyhow I found https://django-nested-admin.readthedocs.io/en/latest/ which seems to solve my problems. Thanks

**Comment by pawnhearts** [comment]
There weren't much tests back when I made that PR(there was just one which just tested if admin site loads). The thing is parent classes all work via that get_inline interface(which can be redefined and I had it redefined in my project). Just like other similar things in django(get_queryset, get_serializer_class, etc).
It's so simple there aren't much to test. That changelist_view still works when this method is redefined? That this method returns value of inlines if it's not?

**Comment by OskarPersson** [comment]
You're right. This is now merged :)

**Pull request merged**
